version: '3.8'

services:
  webapp:
    build: .
    container_name: webapp
    ports:
      - "7007:80"
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    image: mariadb:10.5.11
    container_name: mariadb
    environment:
      - TZ=Europe/Oslo
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - "3308:3306"
    volumes:
      - ./database:/var/lib/mysql
    restart: unless-stopped